Add items table and model
kennethlove/hangry-games pull request #13
Opened 2024-09-16 21:31 UTC by tess-dev-main

This PR adds Items to the database, updates the schema, and creates an Item model.

2024-09-16 21:32 UTC, tess-dev-main commented on hangry_games/migrations/2024-09-16-210408_link_game_and_area_to_items/down.sql
Oops! Noted.

2024-09-16 21:32 UTC, tess-dev-main commented on hangry_games/migrations/2024-09-16-210408_link_game_and_area_to_items/down.sql
Will update.

2024-09-16 21:33 UTC, tess-dev-main commented on hangry_games/migrations/2024-09-16-211214_add_durability_to_items/down.sql
Missed this one too.

2024-09-16 21:36 UTC, kennethlove requested changes
Looks OK but I'd like to see some clean up. This only needs 1 migration so consolidate those down, please. Also make sure every up has a down and both of them have relevant, explanatory comments.

Other than that, seems like a fine PR.

2024-09-16 21:36 UTC, kennethlove commented on hangry_games/migrations/2024-09-16-211214_add_durability_to_items/down.sql
> +-- This file should undo anything in `up.sql`
this down doesn't do anything

2024-09-17 19:33 UTC, kennethlove commented on hangry_games/migrations/2024-09-17-181252_add-items-consolidated/down.sql
> +DROP TABLE items;-- This file should undo anything in `up.sql`
```suggestion
-- Removes the `items` table
DROP TABLE items;
```

2024-09-17 19:33 UTC, kennethlove commented on hangry_games/migrations/2024-09-17-181252_add-items-consolidated/up.sql
> +-- Your SQL goes here
```suggestion
-- Creates `items` table to store...
```

2024-09-17 19:34 UTC, kennethlove approved these changes
Looks good other than the creation comment needing to be filled out. Thanks!

2024-10-05 23:37 UTC, merged